name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ts-check:
    name: TS Compiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: yarn run ts-check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: yarn run build
