name: DevOps

on:
  push:
    branches:
      - main
  pull_request:

env:
  FRONTEND_IMAGE_NAME: prototype-frontend
  ALLOWED_IMAGE_DOMAIN: henken.club

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - uses: bahmutov/npm-install@v1
      - run: yarn run lint:eslint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: yarn run lint:prettier

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: yarn run codegen
      - run: yarn run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: bahmutov/npm-install@v1
      - run: yarn run codegen
      - run: yarn run build
        env:
          ALLOWED_IMAGE_DOMAIN: ${{ env.ALLOWED_IMAGE_DOMAIN }}

  docker-frontend:
    name: Docker for frontend
    needs:
      - typecheck
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/henken-club/${{ env.FRONTEND_IMAGE_NAME }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
